spring:
  application:
    name: session-security
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: sample
    password: sample
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

app:
  security:
    header-session-enabled: true
